name: Daily Video Bot

on:
  schedule:
    - cron: '0 8 * * *' # רץ כל יום ב-8 בבוקר UTC
  workflow_dispatch:      # מאפשר הרצה ידנית

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

    - name: Install Python Dependencies
      run: |
        # הוספנו את requests לרשימה
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client moviepy==1.0.3 requests

    - name: Run Bot
      env:
        CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }} # המפתח החדש
      run: python main.py
